config/routes.rb
Rails.application.routes.draw do
  # get '/students', to: 'students#index', as: 'students'
  # get '/students/new', to: 'students#new', as: 'new_student'
  # post '/students', to: 'students#create'
  # get '/developers', to: 'students#index', as: 'students'
  resources :students, except: [ :destroy ]

  resources :wolves
  # resources :dogs, only: [:index, :new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    student = Student.create( student_params(:name, :email, :dob) )
    redirect_to students_path
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @student.update(student_params(:name, :email, :dob) )
    redirect_to @student
  end

  private

  def student_params(*args)
    params.require(:student).permit(*args)
  end

end


# class PublicKeysController < ApplicationController
#
#   def create
#     params[:public_key] # {user_id: , key: }
#     @public_key = PublicKey.create(params[:public_key])
#   end
#
# end

app/helpers/application_helper.rb
module ApplicationHelper

  # def make_link_to(body, path)
  #   "<a href='#{path}'>#{body}</a>".html_safe
  # end

  # def text_field_tag(field_name)
  #   "<input type='text' name='#{field_name.to_s}' id='#{field_name.to_s}'/>".html_safe
  # end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentLister</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_for( student ) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :dob %>
  <%= f.date_field :dob %>
  <%= f.submit %>
<% end %>

app/views/students/edit.html.erb
<h1>Edit a Student</h1>

<%= render partial: 'form', locals: {student: @student} %>

app/views/students/index.html.erb
<h1>All Students</h1>

<ul>
  <% @students.each do |student| %>
    <li><%= link_to student.name, student %></li>
  <% end %>
</ul>

<%= link_to "Create a Student", new_student_path %>

app/views/students/new.html.erb
<h1>Create a Student</h1>

<%= render partial: 'form', locals: {student: @student} %>

<%= link_to "Back", students_path %>

app/views/students/show.html.erb
<h1><%= @student.name %></h1>
<p><%= @student.email %></p>

<%= link_to "Back", students_path %>
<%= link_to "Edit", edit_student_path(@student) %>